### ISSUE TITLE
creditsafe Doesn't work in odoo 16 EE

### ISSUE THREAD

**Issue by respartner** [article714/coreff#11]
Got this traceback related to coreff_connector.py for the creditsafe module.

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/tools/safe_eval.py", line 339, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/odoo/src/user/article714/coreff/coreff_creditsafe/models/coreff_connector.py", line 272, in creditsafe_get_company
    if arguments["as_pdf"]
KeyError: 'as_pdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 1579, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/home/odoo/src/odoo/odoo/http.py", line 1608, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/odoo/http.py", line 1805, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 144, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 698, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/user/article714/coreff/coreff_creditsafe/models/res_partner.py", line 271, in retrieve_directors_data
    company = self.env["coreff.api"].get_company(arguments)
  File "/home/odoo/src/user/article714/coreff/coreff_base/models/coreff_api.py", line 38, in get_company
    return safe_eval(
  File "/home/odoo/src/odoo/odoo/tools/safe_eval.py", line 353, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
ValueError: <class 'KeyError'>: "as_pdf" while evaluating
'self.creditsafe_get_company(arguments)'

**Comment by chrisandrewmann** [comment]
Hi @respartner 
I have made several outstanding Pull Requests for bugfixes, V16 upgrade and adding PDF download feature. Yet to be approved.

**Comment by respartner** [comment]
Hi @chrisandrewmann 
That's good to hear. Thank you very much :)

**Comment by xtof-osd** [comment]
Hello @respartner & @chrisandrewmann ,
sorry for the loonngg delay, I'll try to review the PR this week, and merge ASAP.
Thank you very much @chrisandrewmann for the evolutions.

**Comment by chrisandrewmann** [comment]
@xtof-osd No problem, thanks for letting me know.
I have had someone using it in production for a few months and so far all working well.

**Comment by xtof-osd** [comment]
> Hi @chrisandrewmann That's good to hear. Thank you very much :)

Hello,
I've meged @chrisandrewmann work, tell me if it fixes your issue. 
We do not user EE here, so we cannot verify this.
Thx

**Comment by chrisandrewmann** [comment]
@xtof-osd This is resolved, please close issue.
I have people using the Creditsafe module successfully in V16 both community and enterprise.
